# DO NOT COMMIT TO GIT
myntra_clv:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: TRANSFORMER_ROLE
      database: SILVER
      warehouse: TRANSFORM_WH
      schema: SILVER_ERP
      threads: 4
      client_session_keep_alive: false
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: TRANSFORMER_ROLE
      database: SILVER_DEV
      warehouse: TRANSFORM_WH
      schema: SILVER_ERP
      threads: 2
      client_session_keep_alive: false