-- ============================================================
-- Run this on the AZURE SQL SOURCE — not on Snowflake
-- Requires ALTER DATABASE permission on the source database
-- Only needed for sources where update_method = NATIVE_UPDATE
-- ============================================================

-- SOURCE: SRC-001 (ERP)
ALTER DATABASE {{PLACEHOLDER_SRC_001_DB}}
    SET CHANGE_TRACKING = ON
    (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

ALTER TABLE [Schema].OE_ORDER_HEADERS_ALL ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].OE_ORDER_LINES_ALL ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].ADDRESSES ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].CITY_TIER_MASTER ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].MTL_SYSTEM_ITEMS_B ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].CATEGORIES ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].BRANDS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

-- SOURCE: SRC-002 (CRM)
ALTER DATABASE {{PLACEHOLDER_SRC_002_DB}}
    SET CHANGE_TRACKING = ON
    (CHANGE_RETENTION = 2 DAYS, AUTO_CLEANUP = ON);

ALTER TABLE [Schema].Customers ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].CustomerRegistrationSource ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].INCIDENTS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].INTERACTIONS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
ALTER TABLE [Schema].SURVEYS ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);

-- Verification query (run after enabling)
SELECT t.name AS table_name,
       ct.is_track_columns_updated_on
FROM sys.tables t
JOIN sys.change_tracking_tables ct ON t.object_id = ct.object_id
ORDER BY t.name;